server:
  port: 26666

spring:
  application:
    name: druiddemo
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/metadata_db?characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    druid:
      mysql-db1:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://${DB_HOST}:${DB_PORT}/test?characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        validation-query: SELECT 1
        test-on-borrow: true
      mysql-db2:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://${DB_HOST}:${DB_PORT}/test2?characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        validation-query: SELECT 1
        test-on-borrow: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.lms.multipledatasource.entity

